### ISSUE TITLE
Manual installation no framework 

### ISSUE THREAD

**Issue by nissaba** [ABTSoftware/SciChart.iOS.Examples#8]
https://www.scichart.com/documentation/ios/current/integrating-scichart-libraries.html#integrating-scichart-via-swift-package-manager

It says to grab the framework, problem is that is is kind of missing. Once we download the zip file we do get s folder called SciChart.framework. But this is not useable as is, this needs to build and It seems that the demo project is not able to build it.

**Comment by andriypohorilko** [comment]
Hi there.

If I understand correctly you are trying to install SciChart manually due to cocoapods installation issue described here: https://github.com/ABTSoftware/PodSpecs3.x/issues/2

If you want to consider other than cocoapods installation please follow manual installation steps:
https://www.scichart.com/documentation/ios/current/integrating-scichart-libraries.html#integrating-scichart-manually 

Please note that SciChart isn’t available via Carthage and Swift Package Manager yet.

Let us know if it helped

**Comment by nrudnyk** [comment]
Just a heads up, Swift Package Manager is supported for quite a while now. But since no replies - closing this one.
